-- ============================================================
-- Soft Rituals STORE — Portuguese content (i18n)
-- Run AFTER admin_setup.sql. Additive + idempotent. Safe to re-run.
-- Adds _pt columns and fills Portuguese for all products + sections.
-- ============================================================

alter table public.store_products
  add column if not exists name_pt text,
  add column if not exists short_pt text,
  add column if not exists story_pt jsonb,
  add column if not exists notes_pt jsonb,
  add column if not exists alt_pt text,
  add column if not exists seo_title_pt text,
  add column if not exists seo_description_pt text;

alter table public.store_categories
  add column if not exists name_pt text,
  add column if not exists blurb_pt text;

update public.store_products set name_pt=$pt$Conjunto Dália em Taça$pt$, short_pt=$pt$Uma dália de cera num vaso de cerâmica canelada — com vaso e bandeja próprios.$pt$, story_pt=$pt$["Há quem tenha flores na secretária. Você tem prazos. Este é o meio-termo: uma dália esculpida pétala a pétala em cera cor-de-rosa suave, num vaso de cerâmica canelada que vai guardar muito depois de a vela acabar.","Vem como conjunto — vaso, jarra para flor e bandeja oval — para que o canto da sua secretária seja o único sítio do dia que está acabado, arrumado e calmo."]$pt$::jsonb, notes_pt=$pt$["Dália de cera esculpida à mão","Vaso, jarra e bandeja de cerâmica reutilizáveis","Feito em Maputo"]$pt$::jsonb, alt_pt=$pt$Vela de dália cor-de-rosa num vaso de cerâmica canelada, com jarra para flor e bandeja oval a condizer$pt$, seo_title_pt=$pt$Conjunto Dália em Taça — vela de flor esculpida à mão | Soft Rituals$pt$, seo_description_pt=$pt$Uma dália de cera cor-de-rosa num vaso de cerâmica canelada, com jarra e bandeja a condizer. Vela esculpida à mão, feita em Maputo.$pt$ where slug=$pt$dahlia-bowl-set$pt$;
update public.store_products set name_pt=$pt$Caixa Jardim de Suculentas$pt$, short_pt=$pt$Quatro suculentas de cera sobre seixos verdadeiros. O jardim que lhe sobrevive.$pt$, story_pt=$pt$["Esqueceu-se de regar a última planta. E a anterior também. Este jardim não guarda rancor: um lótus azul-petróleo, uma equevéria verde, um pequeno cato escuro e uma peónia pálida, esculpidos em cera e plantados sobre seixos verdadeiros.","Acenda um pavio de cada vez, ou deixe o conjunto inteiro na prateleira como prova de que algo aos seus cuidados está a prosperar."]$pt$::jsonb, notes_pt=$pt$["Quatro suculentas esculpidas","Assentes sobre seixos verdadeiros","Cuida de si próprio"]$pt$::jsonb, alt_pt=$pt$Quatro velas de suculentas esculpidas, plantadas sobre seixos verdadeiros numa bandeja branca$pt$, seo_title_pt=$pt$Caixa Jardim de Suculentas — conjunto de velas esculpidas | Soft Rituals$pt$, seo_description_pt=$pt$Quatro velas de suculentas esculpidas à mão sobre seixos verdadeiros numa bandeja branca. A planta que não consegue matar. Feito à mão em Maputo.$pt$ where slug=$pt$succulent-garden-box$pt$;
update public.store_products set name_pt=$pt$Pilar Bouquet Esculpido$pt$, short_pt=$pt$Um ramo inteiro esculpido em cera, no rosa mais suave que há.$pt$, story_pt=$pt$["Rosas, lírios e margaridas, esculpidos num só pilar cor-de-rosa suave. Parece algo que lhe dariam no fim de uma semana muito boa — por isso ofereça-o a si própria antes de a semana sequer começar.","Deixe-o arder devagar ao serão e as flores brilham por dentro. Ou não o acenda nunca. Não vamos verificar."]$pt$::jsonb, notes_pt=$pt$["Relevo floral esculpido","Pilar de combustão lenta","Brilha por dentro à medida que arde"]$pt$::jsonb, alt_pt=$pt$Vela em pilar cor-de-rosa suave, esculpida com rosas, lírios e margaridas$pt$, seo_title_pt=$pt$Pilar Bouquet Esculpido — vela de flores em pilar | Soft Rituals$pt$, seo_description_pt=$pt$Um ramo de rosas, lírios e margaridas esculpido num pilar cor-de-rosa de combustão lenta. Vela esculpida à mão, feita em Maputo.$pt$ where slug=$pt$carved-bouquet-pillar$pt$;
update public.store_products set name_pt=$pt$Cubo de Bolhas$pt$, short_pt=$pt$O cubinho creme em que toda a gente pega primeiro.$pt$, story_pt=$pt$["Pequeno, de cantos arredondados e impossível de não pegar. O cubo de bolhas é o equivalente em vela a uma respiração funda — modesto, suave, exatamente o suficiente.","Guarde um ao lado da chaleira. Acenda-o enquanto a água ferve. É este o ritual inteiro, e funciona."]$pt$::jsonb, notes_pt=$pt$["Cabe numa mão","Acabamento creme","Uma primeira vela fácil"]$pt$::jsonb, alt_pt=$pt$Vela cubo de bolhas creme numa caixa de presente de papel kraft sobre papel verde$pt$, seo_title_pt=$pt$Cubo de Bolhas — a vela creme para começar | Soft Rituals$pt$, seo_description_pt=$pt$Um cubinho de cera creme, suave e modesto — a primeira vela mais fácil. Vertido à mão em pequenos lotes em Maputo.$pt$ where slug=$pt$bubble-cube$pt$;
update public.store_products set name_pt=$pt$Estrela-do-Mar & Conchas$pt$, short_pt=$pt$Uma estrela-do-mar cheia de conchas de cera. O mar, sem o trânsito até à Costa do Sol.$pt$, story_pt=$pt$["Cera branca vertida numa estrela-do-mar cinzenta, rematada com conchinhas em azul e creme. Três pavios, para a luz se espalhar como o fim de tarde sobre a água.","Para quem anda sempre a dizer que precisa de um dia de praia e nunca o tira."]$pt$::jsonb, notes_pt=$pt$["Três pavios","Pormenores em conchas de cera","Recipiente em estrela-do-mar esculpido"]$pt$::jsonb, alt_pt=$pt$Vela em forma de estrela com bordo cinzento e cera branca, decorada com conchas de cera$pt$, seo_title_pt=$pt$Estrela-do-Mar & Conchas — vela do mar de três pavios | Soft Rituals$pt$, seo_description_pt=$pt$Uma estrela-do-mar de cera branca com conchas azuis e creme e três pavios. O mar à secretária. Esculpida à mão em Maputo.$pt$ where slug=$pt$starfish-and-shells$pt$;
update public.store_products set name_pt=$pt$Oceano num Copo$pt$, short_pt=$pt$Gel azul-profundo, areia verdadeira, conchinhas. Um aquário que não lhe pede nada.$pt$, story_pt=$pt$["Olhe de perto: areia no fundo, conchas no recife e aquele azul fundo e límpido que só existe na água e neste copo. Levou horas a montar camada a camada. Basta um fósforo para o desfrutar.","Acenda-o na secretária e veja a luz mover-se pelo azul. O mais perto de um mergulho que consegue fazer numa reunião."]$pt$::jsonb, notes_pt=$pt$["Cera em gel por camadas","Pormenores em areia e conchas verdadeiras","Recipiente de vidro redondo"]$pt$::jsonb, alt_pt=$pt$Vela em copo de vidro redondo com cera em gel azul-profundo, areia e conchas como o fundo do mar$pt$, seo_title_pt=$pt$Oceano num Copo — vela em gel azul com areia | Soft Rituals$pt$, seo_description_pt=$pt$Vela em copo de vidro com gel azul-profundo, areia verdadeira e conchas, como o fundo do mar. Feita à mão em Maputo.$pt$ where slug=$pt$ocean-in-a-glass$pt$;
update public.store_products set name_pt=$pt$Pequeno Buda$pt$, short_pt=$pt$Uma figurinha serena em rosa suave. Nunca verificou o email.$pt$, story_pt=$pt$["Ele senta-se. É só isso. É essa a arte. Um pequeno Buda em cera cor-de-rosa suave, perfeitamente contente por não fazer absolutamente nada — o que faz dele o professor mais qualificado lá de casa.","Ponha-o onde o dia fica barulhento: ao lado do portátil, junto ao carregador do telemóvel, no balcão da cozinha às 18h00."]$pt$::jsonb, notes_pt=$pt$["Figura vertida à mão","Cera cor-de-rosa suave","Em caixa, pronto para presente"]$pt$::jsonb, alt_pt=$pt$Vela Buda em rosa suave sentada numa caixa de presente de papel kraft com papel verde$pt$, seo_title_pt=$pt$Pequeno Buda — vela serena em rosa suave | Soft Rituals$pt$, seo_description_pt=$pt$Um pequeno Buda em cera cor-de-rosa suave, vertido à mão e pronto para presente. Cinco minutos de calma, feitos em Maputo.$pt$ where slug=$pt$little-buddha$pt$;
update public.store_products set name_pt=$pt$Latte Gelado$pt$, short_pt=$pt$Um latte cremoso coberto de chocolates de cera. Zero cafeína depois das 17h00.$pt$, story_pt=$pt$["Já tomou o último café do dia — o seu médico, o seu cônjuge e o seu sono estão todos de acordo. Este é de cera: um latte cremoso num copo canelado, coberto de pequenas gotas de chocolate.","Acenda-o à hora a que costumava encher outra chávena. O mesmo conforto. Uma noite melhor."]$pt$::jsonb, notes_pt=$pt$["Copo canelado","Cobertura de chocolates de cera","O descafeinado que nem sequer é café"]$pt$::jsonb, alt_pt=$pt$Vela Latte Gelado — latte cremoso de cera num copo canelado coberto de chocolates de cera$pt$, seo_title_pt=$pt$Latte Gelado — vela de sobremesa em cera | Soft Rituals$pt$, seo_description_pt=$pt$Um latte cremoso de cera num copo canelado, coberto de chocolates. Vela artesanal feita à mão em Maputo. Pequenos rituais, grande calma.$pt$ where slug=$pt$iced-latte$pt$;
update public.store_products set name_pt=$pt$Matcha de Morango$pt$, short_pt=$pt$Chá verde e morangos num copo fosco. Fresco, doce, muito calmo.$pt$, story_pt=$pt$["Verde de matcha vertido sobre rosa de fruta, num copo fosco que apanha a luz da tarde. Dois morangos de cera repousam no topo como quem não tem mais nada para fazer.","É a vela para a hora devagar — aquela que continua a prometer a si mesma e que finalmente vai tirar."]$pt$::jsonb, notes_pt=$pt$["Cera em camadas, verde e rosa","Copo fosco texturado","Cobertura de morango em cera"]$pt$::jsonb, alt_pt=$pt$Vela Matcha de Morango — cera verde com dois morangos de cera num copo fosco$pt$, seo_title_pt=$pt$Matcha de Morango — vela de sobremesa | Soft Rituals$pt$, seo_description_pt=$pt$Chá verde e morangos de cera num copo fosco, fresco e doce. Vela artesanal feita à mão em Maputo. Pequenos rituais, grande calma.$pt$ where slug=$pt$strawberry-matcha$pt$;
update public.store_products set name_pt=$pt$Flor de Primavera$pt$, short_pt=$pt$Flores secas verdadeiras suspensas em cera transparente. A primavera, presa num copo.$pt$, story_pt=$pt$["Pequenos botões e pétalas secas, suspensos em cera transparente como se a primeira semana de primavera tivesse decidido ficar. Cada Flor de Primavera é diferente, porque cada punhado de flores também é.","À medida que arde, a luz encontra as pétalas uma a uma. É a forma mais lenta possível de olhar para flores — o que é, precisamente, a ideia."]$pt$::jsonb, notes_pt=$pt$["Flores secas verdadeiras","Cera transparente, copo quadrado","Cada uma é única"]$pt$::jsonb, alt_pt=$pt$Vela Flor de Primavera — cera transparente com flores secas verdadeiras num copo quadrado$pt$, seo_title_pt=$pt$Flor de Primavera — vela com flores secas | Soft Rituals$pt$, seo_description_pt=$pt$Flores secas verdadeiras suspensas em cera transparente, num copo quadrado. Vela artesanal feita à mão em Maputo. Cada uma única.$pt$ where slug=$pt$blossom$pt$;
update public.store_products set name_pt=$pt$Taça de Guloseimas$pt$, short_pt=$pt$Chantili, rebuçados, morangos, um waffle — tudo em cera, tudo seu.$pt$, story_pt=$pt$["Todas as guloseimas que lhe disseram para deixar de comer, reunidas num só copo: chantili, bombons, morangos, um pequeno waffle de chocolate. Calorias: zero. Alegria: completa.","É a coisa mais barulhenta que fazemos e, ainda assim, continua a dizer relaxe."]$pt$::jsonb, notes_pt=$pt$["Coberturas esculpidas à mão em cera","Taça de vidro facetado","Zero calorias, todas elas"]$pt$::jsonb, alt_pt=$pt$Vela Taça de Guloseimas coberta de chantili de cera, rebuçados, morangos e um waffle$pt$, seo_title_pt=$pt$Taça de Guloseimas — vela de sobremesa | Soft Rituals$pt$, seo_description_pt=$pt$Chantili, rebuçados, morangos e waffle, tudo em cera, numa taça facetada. Vela artesanal feita à mão em Maputo. Zero calorias.$pt$ where slug=$pt$candy-sundae$pt$;
update public.store_products set name_pt=$pt$Taça de Frutos Vermelhos$pt$, short_pt=$pt$Uma taça de cristal com frutos de cera e tampa própria. O centro de mesa que não derrete no calor.$pt$, story_pt=$pt$["Camadas de cera vermelha, dourada e transparente, salpicadas de frutos escuros, numa taça de cristal a sério com uma tampa de cristal a sério. Parece o almoço de domingo em casa da sua tia, a boa.","Três pavios sob a superfície. Guarde a tampa para quando os convidados ficarem curiosos."]$pt$::jsonb, notes_pt=$pt$["Taça de cristal com tampa","Três pavios","Camadas de frutos em pormenor"]$pt$::jsonb, alt_pt=$pt$Vela de frutos vermelhos numa taça de cristal com tampa — camadas vermelhas e douradas com frutos de cera$pt$, seo_title_pt=$pt$Taça de Frutos Vermelhos — vela com tampa | Soft Rituals$pt$, seo_description_pt=$pt$Frutos de cera em camadas numa taça de cristal com tampa, três pavios. Vela artesanal feita à mão em Maputo. Pequenos rituais, grande calma.$pt$ where slug=$pt$berry-trifle-bowl$pt$;
update public.store_products set name_pt=$pt$Spritz de Frutos Vermelhos$pt$, short_pt=$pt$Um spritz cor-de-rosa num copo de rebordo dourado. Happy hour, sem dor de cabeça.$pt$, story_pt=$pt$["Gel cor-de-rosa vertido sobre framboesas de cera e cerejas escuras, num copo de pé alto com rebordo dourado. Levante-o contra a janela e é sexta-feira, diga o calendário o que disser.","O único cocktail que melhora a sua noite e a sua segunda-feira."]$pt$::jsonb, notes_pt=$pt$["Copo de pé alto com rebordo dourado","Cera em gel com pormenores de frutos","Sem ressaca incluída"]$pt$::jsonb, alt_pt=$pt$Vela Spritz de Frutos Vermelhos — cera em gel cor-de-rosa com frutos de cera num copo de rebordo dourado$pt$, seo_title_pt=$pt$Spritz de Frutos Vermelhos — vela de sobremesa | Soft Rituals$pt$, seo_description_pt=$pt$Gel cor-de-rosa com framboesas e cerejas de cera num copo de rebordo dourado. Vela artesanal feita à mão em Maputo. Sem ressaca.$pt$ where slug=$pt$berry-spritz$pt$;
update public.store_products set name_pt=$pt$Trio de Túlipas$pt$, short_pt=$pt$Três túlipas em vela sobre um leito de verde. Um ramo que não murcha.$pt$, story_pt=$pt$["Túlipas brancas, vermelhas e amarelas sobre um leito de relva de papel verde, numa caixa kraft com janela. As flores murcham até quinta-feira; estas esperam com toda a paciência o tempo que precisar.","O presente para quem tem tudo, menos vinte minutos de sossego."]$pt$::jsonb, notes_pt=$pt$["Três túlipas esculpidas","Caixa kraft com janela","Pronta a oferecer tal como está"]$pt$::jsonb, alt_pt=$pt$Três velas em forma de túlipa — branca, vermelha e amarela — numa caixa de presente kraft sobre relva de papel verde$pt$, seo_title_pt=$pt$Trio de Túlipas — velas em ramo que não murcha | Soft Rituals$pt$, seo_description_pt=$pt$Três túlipas esculpidas à mão numa caixa de presente kraft. Um ramo que dura, feito à mão em Maputo. Pronto a oferecer.$pt$ where slug=$pt$tulip-trio$pt$;
update public.store_products set name_pt=$pt$Hamsá & Rosa$pt$, short_pt=$pt$Uma mão de bênçãos ao lado de uma rosa creme, juntas numa só caixa.$pt$, story_pt=$pt$["Um hamsá perolado — a mão das bênçãos — pousado ao lado de uma vela em forma de rosa creme, sobre relva de papel verde. Proteção serena e beleza serena, juntas numa caixa.","Para casas novas, bebés novos, capítulos novos e aquelas pessoas por quem rezamos no trânsito."]$pt$::jsonb, notes_pt=$pt$["Hamsá cheio de pormenor","Vela em forma de rosa creme","Caixa kraft com janela"]$pt$::jsonb, alt_pt=$pt$Mão hamsá perolada ao lado de uma vela em forma de rosa creme numa caixa de presente kraft$pt$, seo_title_pt=$pt$Hamsá & Rosa — vela de bênçãos e beleza | Soft Rituals$pt$, seo_description_pt=$pt$Vela hamsá perolada e rosa creme, esculpidas à mão em Maputo, juntas numa caixa de presente. Proteção e beleza serenas.$pt$ where slug=$pt$hamsa-and-rose$pt$;
update public.store_products set name_pt=$pt$Caixa de Bolinhos$pt$, short_pt=$pt$Velas de cupcake e gelado em tons de rosa. O bolo de aniversário que não acaba.$pt$, story_pt=$pt$["Pequenos cupcakes e cones de gelado em todos os tons de rosa, aninhados numa caixa branca. Chega com ar de montra de pastelaria e assim se mantém.","Envie-a em vez de bolo àquela amiga que «este ano não festeja aniversários». Depois veja-a festejar."]$pt$::jsonb, notes_pt=$pt$["Velas de sobremesa sortidas","Apresentação de presente em rosa","À prova de aniversário"]$pt$::jsonb, alt_pt=$pt$Velas de cupcake e gelado em tons de rosa numa caixa de presente branca com papel cor-de-rosa$pt$, seo_title_pt=$pt$Caixa de Bolinhos — velas de sobremesa em rosa | Soft Rituals$pt$, seo_description_pt=$pt$Velas de cupcake e gelado em tons de rosa, feitas à mão em Maputo, numa caixa de presente. O bolo de aniversário que dura.$pt$ where slug=$pt$cupcake-box$pt$;
update public.store_products set name_pt=$pt$Sabonete de Melancia$pt$, short_pt=$pt$Em camadas, como a fruta verdadeira. O sabonete mais alegre da casa de banho.$pt$, story_pt=$pt$["Vermelho, branco e verde, em camadas como uma fatia a sério — sementes incluídas. Transforma os dois minutos ao lavatório na parte mais leve do seu dia.","Feito em pequenos lotes; quando esgota, fazemos mais. Devagar."]$pt$::jsonb, notes_pt=$pt$["Desenho em fatia de camadas","Suave para a pele","Pequenos lotes"]$pt$::jsonb, alt_pt=$pt$Ilustração do sabonete de Melancia — fatia em camadas vermelha, branca e verde$pt$, seo_title_pt=$pt$Sabonete de Melancia — vertido à mão | Soft Rituals$pt$, seo_description_pt=$pt$Sabonete de melancia em camadas, feito à mão em Maputo. Suave para a pele e o mais alegre da casa de banho.$pt$ where slug=$pt$organic-watermelon-soap$pt$;
update public.store_products set name_pt=$pt$Sabonete de Citrinos e Ervas$pt$, short_pt=$pt$Dourado e transparente, salpicado de ervas verdadeiras. Limpo como um jardim.$pt$, story_pt=$pt$["Um disco dourado e cristalino salpicado de ervas verdadeiras. Cheira a um jardim que outra pessoa trata — fresco, cítrico, sem esforço.","Melhor usado devagar, no fim dos dias que correram depressa."]$pt$::jsonb, notes_pt=$pt$["Salpicos de ervas verdadeiras","Sabonete dourado e transparente","Fresco e cítrico"]$pt$::jsonb, alt_pt=$pt$Ilustração do sabonete de Citrinos e Ervas — disco dourado salpicado de ervas$pt$, seo_title_pt=$pt$Sabonete de Citrinos e Ervas — fresco | Soft Rituals$pt$, seo_description_pt=$pt$Sabonete dourado de citrinos com ervas verdadeiras, feito à mão em Maputo. Fresco, cítrico e limpo como um jardim.$pt$ where slug=$pt$citrus-herb-soap$pt$;
update public.store_products set name_pt=$pt$Sabonetes Jardim de Flores$pt$, short_pt=$pt$Margaridas, rosas e flores — um ramo com que se pode lavar.$pt$, story_pt=$pt$["Sabonetes com a forma de um ramo de feira de domingo: margaridas, rosas, pequenas flores. Bonitos demais para a saboneteira, e é precisamente por isso que pertencem ali.","Guarde-os para as visitas, ou admita que também é visita em sua própria casa e use-os esta noite."]$pt$::jsonb, notes_pt=$pt$["Variadas formas de flores","Suave para a pele","Dignos de visita, dignos de si"]$pt$::jsonb, alt_pt=$pt$Ilustração dos sabonetes Jardim de Flores — sabonetes em forma de margarida e de flor$pt$, seo_title_pt=$pt$Sabonetes Jardim de Flores — esculpidos à mão | Soft Rituals$pt$, seo_description_pt=$pt$Sabonetes em forma de flores, esculpidos à mão em Maputo. Um ramo bonito demais para guardar — use-o esta noite.$pt$ where slug=$pt$flower-garden-soaps$pt$;

update public.store_categories set name_pt=$pt$Velas$pt$, blurb_pt=$pt$Esculpidas à mão, vertidas uma a uma.$pt$ where slug=$pt$candles$pt$;
update public.store_categories set name_pt=$pt$Velas Doces$pt$, blurb_pt=$pt$Parecem deliciosas. São de cera.$pt$ where slug=$pt$dessert-candles$pt$;
update public.store_categories set name_pt=$pt$Caixas de Presente$pt$, blurb_pt=$pt$Embrulhadas, etiquetadas e prontas a oferecer.$pt$ where slug=$pt$gift-boxes$pt$;
update public.store_categories set name_pt=$pt$Sabonetes$pt$, blurb_pt=$pt$Suaves na pele, feitos em pequenos lotes.$pt$ where slug=$pt$soaps$pt$;
