// Generates supabase/store_seed.sql from lib/products.ts so the
// database always matches the code. Run: node scripts/gen-seed.mts
import { PRODUCTS } from "../lib/products.ts";
import { writeFileSync } from "node:fs";

const q = (s: string) => `'${s.replace(/'/g, "''")}'`;
const j = (v: unknown) => `'${JSON.stringify(v).replace(/'/g, "''")}'::jsonb`;

const rows = PRODUCTS.map(
  (p) =>
    `(${q(p.slug)}, ${q(p.name)}, ${q(p.category)}, ${p.price}, ${q(p.image)}, ${q(p.alt)}, ${q(p.short)}, ${j(p.story)}, ${j(p.notes)}, ${p.featured ? "true" : "false"}, ${q(p.seoTitle)}, ${q(p.seoDescription)})`
).join(",\n  ");

const sql = `-- Generated by scripts/gen-seed.mts — do not edit by hand.
-- Paste into Supabase SQL Editor AFTER store_schema.sql.
insert into public.store_products
  (slug, name, category, price, image, alt, short, story, notes, featured, seo_title, seo_description)
values
  ${rows}
on conflict (slug) do update set
  name = excluded.name,
  category = excluded.category,
  price = excluded.price,
  image = excluded.image,
  alt = excluded.alt,
  short = excluded.short,
  story = excluded.story,
  notes = excluded.notes,
  featured = excluded.featured,
  seo_title = excluded.seo_title,
  seo_description = excluded.seo_description,
  active = true;
`;

writeFileSync(new URL("../supabase/store_seed.sql", import.meta.url), sql);
console.log(`Wrote supabase/store_seed.sql (${PRODUCTS.length} products)`);
